### ISSUE TITLE
[error] passing function to the component via bindings

### ISSUE THREAD

**Issue by vcollado** [rickhub/ng-compile-component#2]
Hi,
While ussing this library in a project, I found that passing down a function in bindings does not render as expected, where 
`on-update="$ctrl.handleUpdate($event)` 
 becomes
 `on-update="$ctrl["onUpdate"]"` 

at 
**ng-compile-component-service.js**

I have made a workaround adding the library locally to my project and fixing the the render function with 
`attrs += ' ' + toLowerDash(prop) + '=\'' + '$ctrl["' + prop + '"]($event)' + '\'';`

maybe I'm missing something or if you want I can make a pull request with my changes

thanks in advice

**Comment by rickhub** [comment]
Hey, sorry for the late response. I actually release version `3.x` of the library. You can now use the new `config` property for specifying binding types manually. It's also possible to render an attribute by yourself:

    this.config = {
        onUpdate: function(attr, value){
            return `on-update="$ctrl.onUpdate($event);"`;
        }
    };

    <ng-compile-component component='..' bindings='..' config='$ctrl.config'></ng-compile-component>

Happy coding :-)
