### ISSUE TITLE
Two way binding as a string

### ISSUE THREAD

**Issue by ewantavenerdemo** [rickhub/ng-compile-component#3]
Hey,

I'm using your awesome component compiler. I have the following issues:

- if I have a string that is two way binding it errors because it thinks it's '@' and not '='
- The angular module and files are not packaged properly.

**Comment by rickhub** [comment]
Hey, sorry for the late response. I updated the component to version `3.x`. This release ships a brand new `config` attribute that can be used to specify binding types manually:

    <ng-compile-component
        component='myComponent'
        bindings='{
            string: "simple",
            twoWayString: "yes, two way!"
        }'
        config='{
            twoWayString: "="
        }'
    ></ng-compile-component>

Have fun with it :-)
