### ISSUE TITLE
ng-compile-component is not working with component with inline template.

### ISSUE THREAD

**Issue by VeeteshJain** [rickhub/ng-compile-component#4]
ng-compile-component is not working with a component with the inline template but it works when templateUrl was used.

refer this plnkr https://plnkr.co/edit/E3qBQz?p=preview

<img width="1438" alt="screen shot 2018-04-02 at 2 44 41 pm" src="https://user-images.githubusercontent.com/6864682/38191052-abb917ac-3684-11e8-9639-3d5cc4ec765c.png">

**Comment by rickhub** [comment]
Hey, thanks for the report. I don't think that this is a templateUrl / template issue. I created this fiddle to test it: https://jsfiddle.net/orf1wxw6/ (angular 1.6.10)

Maybe this will help you.
